server:
  port: 8090

spring:
  rabbitmq:
    password: guest
    host: localhost
    port: 5672
    username: guest

  cloud:
    stream:
      function:
        definition: rabbitConsumer
      bindings:
        rabbitConsumer-in-0:
          destination: queueName
          group: queueGroup
      rabbit:
        bindings:
          rabbitConsumer-in-0:
            consumer:
              auto-bind-dlq: true
api:
  url: url_api
  endpoints:
    coleta: collect_endpoint
    auth: auth_endpoint
usuario: usr
senha: psrd